Simplify autoresponder logic
Grasscutters/lawnmower pull request #24
Opened 2023-03-10 19:06 UTC by thecutefinder

There is no longer a dedicated Chinese support channel, so it's unnecessary to check if a thread is in the Chinese support channel.

2023-03-10 19:09 UTC, memetrollsXD requested changes

2023-03-10 19:10 UTC, thecutefinder commented on src/events/messageCreate.ts
> +    if (message.channelId === "1082829744363548762" && message.deletable) { // #verify
Accidentally changed that to the wrong one in testing

2023-03-10 19:11 UTC, thecutefinder commented on src/events/messageCreate.ts
> +                message.reply(action.action);
Yes, but we would have to upgrade to a newer Discord.JS version, which would require re-writing a lot of the bot's code, due to the newer versions changing class and variable names.

2023-03-10 19:13 UTC, thecutefinder commented on src/events/messageCreate.ts
> +                message.reply(action.action);
I can work on that later today.

2023-03-10 19:15 UTC, memetrollsXD approved these changes
Channel ID is proper now, although the Chinese reply is gone without any replacement, I haven't seen a lot of Chinese support posts anyway, so this will do for now since it's only a utility

2023-03-10 19:15 UTC, merged

2023-03-11 01:12 UTC, thecutefinder commented
@memetrollsXD Just so you know, I've looked into trying to check the tags to add a CN reply and check the post title to match keywords based on that as well.

Post title is possible using the `threadCreate` event for each new post in #support. Given that the bot will add a reaction once it's responded, you can check the reaction count to prevent race conditions in which a keyword has been matched in both the contents and title. This could be made more efficient and work better for cases where the same keyword has duplicated by checking replies in the thread and making sure that the same response hasn't already been sent, but I'm a bit ~~lazy~~ busy right now and don't want to look into it.

As for the tags: This is what confuses me the most. Okay, so, when using the `messageCreate` event, you cannot check what thread the post is inside of. You CAN check what forum it's inside of, but that's the most. Therefore, unless we do something really complicated<sup>1</sup>, the tags can only be checked in the `threadCreate` event using a tags attribute (and therefore we can only switch between CN and EN responses in replies to the initial forum post, not in subsequent messages). HOWEVER, it does not return tag names or any objects, only their IDs, and I have *no idea* how to get tag IDs. I have developer mode on and everything in Discord, but I simply *cannot* find any way to initiate a dropdown or copy the IDs for any tags. I looked everywhere that tags are listed and I cannot find anything. I'll probably have to open DevTools and find it manually or something.

<sup>1</sup> You would have to check all open in threads in some way (I think there is some way to fetch them all at once), and then in `messageCreate`, find where new messages match up exactly with something stored in an open thread. Using this, you could check the thread metadata and such, including the IDs of any tags, and use this to choose to either write a CN or EN comment. However, this is very, very complicated, and I don't want to do it right now.